name: snakemake
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - mamba
  - snakemake
  - git # Not strictly necessary, but nice to have.



# Create an environment from this file by calling
# conda env create -f environment.yaml
