name: snakemake
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - mamba
  - snakemake
  - git # Not strictly necessary, but nice to have.


# conda env create -f environment.yaml

