  
#cores: 16 # good guy
cores: 64 # not a good guy 
# I think The Epycs have 64 physical cores which become 128 with hyperthreading

keep-going: true 
rerun-incomplete: false
show-failed-logs: true
keep-incomplete: false

use-conda: true
conda-frontend: mamba


default-resources:
  - tmpdir='/mnt/hpccs01/scratch/microbiome/kobel'

