
local-cores: 16 # front end / head node cores
cores: 2048 # cluster cores
jobs: 1000 # max parallel jobs
keep-going: true 
#rerun-incomplete: true
latency-wait: 120 # Some file systems can be slow.
keep-incomplete: true # Should be true for debugging rules.

# This one could be cool to have working 
show-failed-logs: true


# ---- Conda/Mamba/Apptainer ----
use-conda: true
conda-frontend: 'mamba' # Make sure that you install mamba in the environment where you're calling snakemake. Muuuuch faster than conda.
#use-singularity: true


# ---- Sigma2 Saga SLURM specifics ----

cluster-cancel: "scancel"

cluster:
  mkdir -p logs/ &&
  sbatch
    --parsable
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=ac2_{rule}_{wildcards}
    --output=logs/{jobid}-{rule}.out.log
    --error=logs/{jobid}-{rule}.err.log
    --time={resources.runtime}
    --account=ClinicalMicrobio # ClinicalMicrobio or supacow

 
#--partition={resources.partition}
    



default-resources:
  - mem_mb=1024
  #- disk_mb=1024 # genomedk doesn't care 
  - runtime='12:00:00'
  - tmpdir='$SCRATCH'
  #- partition=normal # genomedk doesn't care too much about partitions (https://genome.au.dk/docs/interacting-with-the-queue/#why-is-the-partition-i-chose-being-ignored)
  




